# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eProQA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'FPStepView', '~> 1.0'
	pod 'SwiftyJSON', '~> 4.0'
  # Pods for eProQA

end
